### ISSUE TITLE
Can not execute "java -jar target/floodlight.jar"

### ISSUE THREAD

**Issue by chiyue** [floodlight/floodlight#469]
i have finished installation. when i executed "java -jar target/floodlight.jar",the ubuntu always pauses at “12:49:11.388 [debugserver-main] INFO n.f.jython.JythonServer - Starting DebugServer on port 6655”.

**Comment by rizard** [comment]
@chiyue Did you resolve this issue?

**Comment by rizard** [comment]
@chiyue I'm going to close this to keep the issues "clean." Feel free to open it back up if your questions haven't been addressed.
