### ISSUE TITLE
a bug ?

### ISSUE THREAD

**Issue by wenxueliu** [floodlight/floodlight#471]
" 580         } else if (eth.getEtherType() < 1500) {  "  

what's meaning in  LinkDiscoveryManager.java of learningswitch with openflow1.3 branch 。

**Comment by rizard** [comment]
@3mp4y5 How's this look?

              else if (eth.getEtherType() < 1536 && eth.getEtherType() >= 17) {
			long destMac = eth.getDestinationMACAddress().getLong();
			if ((destMac & LINK_LOCAL_MASK) == LINK_LOCAL_VALUE) {
				ctrLinkLocalDrops.increment();
				if (log.isTraceEnabled()) {
					log.trace("Ignoring packet addressed to 802.1D/Q "
							+ "reserved address.");
				}
				return Command.STOP;
			}
		} else if (eth.getEtherType() < 17) {
			log.error("Received invalid ethertype of {}.", eth.getEtherType());
			return Command.STOP;
		}

**Comment by rizard** [comment]
Fixed.

**Comment by 3mp4y5** [comment]
--nice-- thanks!
