### ISSUE TITLE
How to Config with vlan ?

### ISSUE THREAD

**Issue by Cookie-Wang** [floodlight/floodlight#483]
hi:
i want use floodlight with xenserver,when i connect to the floodlight ,the xenserver's port with vlan tag ,can not ping 。
can you tell me how to config flow in floodlight?
i add this flow:port 14 has vlan tag:
cookie=0xa00000ec83e777, duration=4114.541s, table=0, n_packets=2786, n_bytes=248759, priority=16383,in_port=14 actions=NORMAL 

the port with vlan tag can ping .bug the firewall is failure.

my email:wangyuyang1985@163.com

thanks.

**Comment by rizard** [comment]
@Cookie-Wang The NORMAL action should tell the switch to forward the packet as it would as a learning switch. This sounds like it's working if you can ping and that's the type of flows you are inserting.

What about the firewall isn't working? What exactly are you trying to accomplish? (Sorry for getting to this so late...Feel free to use the mailing list in the future for a more rapid reply. More people are active on that than on the GitHub issues.)

**Comment by rizard** [comment]
@Cookie-Wang have you resolved the issue?

**Comment by rizard** [comment]
@Cookie-Wang I'm going to close this issue to keep the list clean. Please reopen if you have another question.
