### ISSUE TITLE
debugcounter module bug

### ISSUE THREAD

**Issue by wenxueliu** [floodlight/floodlight#484]
`CounterNode remove(List<String> hierarchyElements)`  in  CounterNode.java,  if the hierarchyElements is empty， `String keyToRemove = hierarchyElements.remove(hierarchyElements.size() - 1)` will throw IndexOutOfBoundsException, it should return null and log it if hierarchyElements.isEmpty()

**Comment by rizard** [comment]
@wenxueliu Thanks for pointing this out! Would you like to issue a pull request? If not, I'll change it myself quick.

**Comment by rizard** [comment]
@wenxueliu I just patched it.
