### ISSUE TITLE
How can floodlight get the "Slient Server" MAC?

### ISSUE THREAD

**Issue by TINCEHUANG** [floodlight/floodlight#486]
"Silent Server" means a server won't actively broadcast or send any packet(i.e. ARP, ICMPV6). When floodlight work as a LoadBalancer, how could it get the server MAC so that they can correctly forward the packet? 
In another case, the client have already had Server MAC before controller have that (it won't send ARP request so controller can't learn the ip&mac from server's ARP reply),.

**Comment by rizard** [comment]
If I'm understanding this correctly, you want to use the LoadBalancer with a server that does not broadcast any packets? In that case, you'll need to have some way of telling Floodlight the server is there. Maybe the server can send a unicast packet (e.g. UDP) to some arbitrary address. When that packet reaches the OF switch, Floodlight will learn where the server is as well as it's IP and MAC addresses.

Floodlight can only learn where a device attachment point is if sees a packet generated by that device on a particular switch port.

**Comment by rizard** [comment]
@TINCEHUANG I'm going to close this to keep the issues "clean." Feel free to open it back up if your questions haven't been addressed.
