### ISSUE TITLE
Unable to build Floodlight Eclipse Project

### ISSUE THREAD

**Issue by activatedgeek** [floodlight/floodlight#487]
I am receiving a build error in the following package: `net.floodlightcontroller.util.MatchUtils` in file `MatchUtils.java`.
This is the full error description:

`The method setMasked(MatchField<F>, Masked<F>) in the type Match.Builder is not applicable for the arguments (MatchField, Masked)`

on lines 141 and 148 in the call `mb.setMasked(mf, m.getMasked(mf));`.

Configurations:
Version: `1.0`
OS: `Mac OS X 10.10`
Java (`java -version` output): 
`java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)`

Can somebody help me get around this issue?

**Comment by rizard** [comment]
The Match is type-safe and requires your Masked type be the same as your MatchField. For example, this will not compile:

match.setMasked(MatchField.ETH_SRC, IPv4AddressWithMask("10.0.0.1/24"))

but this will:

match.setMasked(MatchField.IPV4_SRC, IPv4AddressWithMask("10.0.0.1/24"))

If you did not modify the MatchUtils.java file, I would recommend running Java 7. I have not tested with Java 8. Are you calling a function in MatchUtils from within your module? That might also be the source of the error if you have an ill-formed Match (which should itself cause a compile error).

**Comment by activatedgeek** [comment]
I have not started writing my modules yet. I was just setting up. So, this error is coming up from within the source. I will run on Java 7 and report back.

**Comment by activatedgeek** [comment]
It works with Java SE 1.7. But it would be great if you could get this working with Version 8 as well.

**Comment by Linerd** [comment]
I ran into the same problem, OS: ubuntu 14.04. It appears with oracle-java-8 and still exists with openjdk-1.7, any suggestions?

**Comment by rizard** [comment]
What's your default jre? Make sure it's set to 1.7.

Sent from my iPhone

--
Ryan Izard
Graduate Research/Teaching Assistant
306B Fluor Daniel Building
ECE Department, Clemson University
Clemson, SC 29634
rizard@g.clemson.edu

**Comment by Linerd** [comment]
It is indeed 1.7. I am trying Java SE 1.7, see if it works. Neither 'ant' nor 'ant eclipse' fails, it is just annoying to problem warning in Eclipse and I have not yet tested if it functions normally.
 
From: Ryan Izard
Date: 2015-03-26 17:01
To: floodlight/floodlight
CC: Yikai
Subject: Re: [floodlight] Unable to build Floodlight Eclipse Project (#487)
What's your default jre? Make sure it's set to 1.7.

Sent from my iPhone

--
Ryan Izard
Graduate Research/Teaching Assistant
306B Fluor Daniel Building
ECE Department, Clemson University
Clemson, SC 29634
rizard@g.clemson.edu

**Comment by rizard** [comment]
There are a couple warnings present. Is that's the issue? If so, you should be able to run the controller fine.

Sent from my iPhone

--
Ryan Izard
Graduate Research/Teaching Assistant
306B Fluor Daniel Building
ECE Department, Clemson University
Clemson, SC 29634
rizard@g.clemson.edu

**Comment by Linerd** [comment]
They are errors, not warnings, if that is what you asked. Exactly the same as the guy showed above.

From: Ryan Izard
Date: 2015-03-26 17:06
To: floodlight/floodlight
CC: Yikai
Subject: Re: [floodlight] Unable to build Floodlight Eclipse Project (#487)
There are a couple warnings present. Is that's the issue? If so, you should be able to run the controller fine.

Sent from my iPhone

--
Ryan Izard
Graduate Research/Teaching Assistant
306B Fluor Daniel Building
ECE Department, Clemson University
Clemson, SC 29634
rizard@g.clemson.edu

**Comment by rizard** [comment]
What are they? I can't see the history here.

Sent from my iPhone

--
Ryan Izard
Graduate Research/Teaching Assistant
306B Fluor Daniel Building
ECE Department, Clemson University
Clemson, SC 29634
rizard@g.clemson.edu

**Comment by Linerd** [comment]
The method setMasked(MatchField<F>, Masked<F>) in the type Match.Builder is not applicable for the arguments (MatchField, Masked)
on lines 141 and 148 in the call mb.setMasked(mf, m.getMasked(mf));.
Best
Yikai

From: Ryan Izard
Date: 2015-03-26 17:13
To: floodlight/floodlight
CC: Yikai
Subject: Re: [floodlight] Unable to build Floodlight Eclipse Project (#487)
What are they? I can't see the history here.

Sent from my iPhone

--
Ryan Izard
Graduate Research/Teaching Assistant
306B Fluor Daniel Building
ECE Department, Clemson University
Clemson, SC 29634
rizard@g.clemson.edu

**Comment by rizard** [comment]
I'm pretty sure that's a Java 8 error, which the code isn't compatible with yet. Are you sure Eclipse is set to use Java 7? Check the project properties.

Sent from my iPhone

--
Ryan Izard
Graduate Research/Teaching Assistant
306B Fluor Daniel Building
ECE Department, Clemson University
Clemson, SC 29634
rizard@g.clemson.edu

**Comment by Linerd** [comment]
From: Ryan Izard
Date: 2015-03-26 17:20
To: floodlight/floodlight
CC: Yikai
Subject: Re: [floodlight] Unable to build Floodlight Eclipse Project (#487)
I'm pretty sure that's a Java 8 error, which the code isn't compatible with yet. Are you sure Eclipse is set to use Java 7? Check the project properties.

Sent from my iPhone

--
Ryan Izard
Graduate Research/Teaching Assistant
306B Fluor Daniel Building
ECE Department, Clemson University
Clemson, SC 29634
rizard@g.clemson.edu

**Comment by rizard** [comment]
There are a couple warnings present. Is that's the issue? If so, you should
be able to run the controller fine.

Sent from my iPhone

--
Ryan Izard
Graduate Research/Teaching Assistant
306B Fluor Daniel Building
ECE Department, Clemson University
Clemson, SC 29634
rizard@g.clemson.edu

On Mar 26, 2015, at 5:04 AM, Yikai <notifications@github.com> wrote:

It is indeed 1.7. I am trying Java SE 1.7, see if it works. Neither 'ant'
nor 'ant eclipse' fails, it is just annoying to problem warning in Eclipse
and I have not yet tested if it functions normally.

From: Ryan Izard
Date: 2015-03-26 17:01
To: floodlight/floodlight
CC: Yikai
Subject: Re: [floodlight] Unable to build Floodlight Eclipse Project (#487)
What's your default jre? Make sure it's set to 1.7.

Sent from my iPhone

-- 
Ryan Izard
Graduate Research/Teaching Assistant
306B Fluor Daniel Building
ECE Department, Clemson University
Clemson, SC 29634
rizard@g.clemson.edu

> On Mar 26, 2015, at 3:49 AM, Yikai <notifications@github.com> wrote:
>
> I ran into the same problem, OS: ubuntu 14.04. It appears with
oracle-java-8 and still exists with openjdk-1.7, any suggestions?
>
> —
> Reply to this email directly or view it on GitHub.
>
—
Reply to this email directly or view it on GitHub.

—
Reply to this email directly or view it on GitHub
<https://github.com/floodlight/floodlight/issues/487#issuecomment-86414412>.

**Comment by Linerd** [comment]
I switched from Openjdk-7-jdk to Java SE 1.7, and the errors were gone. Warnings do exist.
 
From: Ryan Izard
Date: 2015-03-26 20:07
To: floodlight/floodlight
CC: Yikai
Subject: Re: [floodlight] Unable to build Floodlight Eclipse Project (#487)
There are a couple warnings present. Is that's the issue? If so, you should
be able to run the controller fine.

Sent from my iPhone

--
Ryan Izard
Graduate Research/Teaching Assistant
306B Fluor Daniel Building
ECE Department, Clemson University
Clemson, SC 29634
rizard@g.clemson.edu

On Mar 26, 2015, at 5:04 AM, Yikai <notifications@github.com> wrote:

It is indeed 1.7. I am trying Java SE 1.7, see if it works. Neither 'ant'
nor 'ant eclipse' fails, it is just annoying to problem warning in Eclipse
and I have not yet tested if it functions normally.

From: Ryan Izard
Date: 2015-03-26 17:01
To: floodlight/floodlight
CC: Yikai
Subject: Re: [floodlight] Unable to build Floodlight Eclipse Project (#487)
What's your default jre? Make sure it's set to 1.7.

Sent from my iPhone

-- 
Ryan Izard
Graduate Research/Teaching Assistant
306B Fluor Daniel Building
ECE Department, Clemson University
Clemson, SC 29634
rizard@g.clemson.edu

> On Mar 26, 2015, at 3:49 AM, Yikai <notifications@github.com> wrote:
>
> I ran into the same problem, OS: ubuntu 14.04. It appears with
oracle-java-8 and still exists with openjdk-1.7, any suggestions?
>
> —
> Reply to this email directly or view it on GitHub.
>
—
Reply to this email directly or view it on GitHub.

—
Reply to this email directly or view it on GitHub
<https://github.com/floodlight/floodlight/issues/487#issuecomment-86414412>.

**Comment by soniekta** [comment]
Hello sir,
HTTPS and SSL are disabled error while floodlight is running in eclipse.
What to do?


09:03:10.678 INFO [n.f.c.m.FloodlightModuleLoader:main] Loading modules from src/main/resources/floodlightdefault.properties
09:03:10.995 WARN [n.f.r.RestApiServer:main] HTTPS disabled; HTTPS will not be used to connect to the REST API.
09:03:10.996 WARN [n.f.r.RestApiServer:main] HTTP enabled; Allowing unsecure access to REST API on port 8080.
09:03:13.398 WARN [n.f.c.i.OFSwitchManager:main] SSL disabled. Using unsecure connections between Floodlight and switches.

**Comment by raghdaaljaff** [comment]
Hello sir I tried to run flowvisor to make multiple floodlight controller 
first I create custom topology in mininet
second I wrote this command
sudo -u flowvisor fvconfig generate /etc/flowvisor /config.json
the error was appeared
sudo :unknown user :flowvisor
sudo :unable to initialize policy plugin 
Can help me in this error ?
