### ISSUE TITLE
Floodlight 1.0, switch listening port can't change by modify floodlightdefault.properties

### ISSUE THREAD

**Issue by pewsheen** [floodlight/floodlight#489]
In floodlight 1.0, I append "net.floodlightcontroller.core.FloodlightProvider.openflowport = 6633" in floodlightdefault.properties but nothing changes. It still listening on 6653.

**Comment by rizard** [comment]
@pewsheen See below for the correct variable name (includes "internal" and the correct case for "openflowPort"):

net.floodlightcontroller.core.internal.FloodlightProvider.openflowPort=6633

**Comment by pewsheen** [comment]
Thanks, it works :)

**Comment by dtiernan357** [comment]
I am having the same problem, where I have changed the listen port in the properties file and in the core directory but still seen in the debug screen: 
20:35:00.633 INFO [n.f.c.i.OFSwitchManager:main] Listening for switch connections on 0.0.0.0/0.0.0.0:6653

where I want it to listen on 6633.

My main problem is, that my hybrid switch is trying to establish a tcp connection to the OF floodlight controller, but the controller always responds with a RST/ACK hence the connection never get establish.

but after the change to the files I am seeing the controller still snding RST/ACK but is using port 6633. As well the debug screen still displays the controller is still listening for 6653.

what files do i need to modify for it to listen on 6633?

properties file has the correct syntax:

net.floodlightcontroller.core.internal.FloodlightProvider.openflowPort=6633

**Comment by rizard** [comment]
Did you save the file and restart the controller?

Sent from my iPhone

--
Ryan Izard
Graduate Research/Teaching Assistant
306B Fluor Daniel Building
ECE Department, Clemson University
Clemson, SC 29634
rizard@g.clemson.edu

**Comment by dtiernan357** [comment]
Yes, l logged out and logged in then ran the Java -jar target/floodlight.jar

**Comment by rizard** [comment]
@dtiernan357 Can you please give the log at the beginning when you start the controller?

Also, check to make sure you only have one controller running at a time.

**Comment by dtiernan357** [comment]
Yes I can in about 45 minutes 

Thanks
Dan

**Comment by dtiernan357** [comment]
Hi Ryan,
Here are the details you requested.

sammy@ubuntu:~$ cd floodlight/
sammy@ubuntu:~/floodlight$ java -jar target/floodlight.jar
08:50:23.373 INFO [n.f.c.m.FloodlightModuleLoader:main] Loading modules from src/main/resources/floodlightdefault.properties
08:50:24.153 WARN [n.f.r.RestApiServer:main] HTTPS disabled; HTTPS will not be used to connect to the REST API.
08:50:24.153 WARN [n.f.r.RestApiServer:main] HTTP enabled; Allowing unsecure access to REST API on port 8080.
08:50:27.247 WARN [n.f.c.i.OFSwitchManager:main] SSL disabled. Using unsecure connections between Floodlight and switches.
08:50:27.247 INFO [n.f.c.i.OFSwitchManager:main] Clear switch flow tables on initial handshake as master: TRUE
08:50:27.247 INFO [n.f.c.i.OFSwitchManager:main] Clear switch flow tables on each transition to master: TRUE
08:50:27.248 INFO [n.f.c.i.OFSwitchManager:main] Setting 0x2 as the default max tables to receive table-miss flow
08:50:27.267 INFO [n.f.c.i.OFSwitchManager:main] Setting max tables to receive table-miss flow to 0x1 for DPID 00:00:00:00:00:00:00:01
08:50:27.267 INFO [n.f.c.i.OFSwitchManager:main] Setting max tables to receive table-miss flow to 0x1 for DPID 00:00:00:00:00:00:00:02
08:50:27.538 INFO [n.f.c.i.OFSwitchManager:main] Computed OpenFlow version bitmap as [62]
08:50:27.554 INFO [n.f.c.i.Controller:main] Controller role set to ACTIVE
08:50:27.610 INFO [n.f.l.i.LinkDiscoveryManager:main] Link latency history set to 10 LLDP data points
08:50:27.610 INFO [n.f.l.i.LinkDiscoveryManager:main] Latency update threshold set to +/-0.5 (50.0%) of rolling historical average
08:50:27.627 INFO [n.f.f.Forwarding:main] Default hard timeout not configured. Using 0.
08:50:27.627 INFO [n.f.f.Forwarding:main] Default idle timeout not configured. Using 5.
08:50:27.628 INFO [n.f.f.Forwarding:main] Default priority not configured. Using 1.
08:50:27.628 INFO [n.f.f.Forwarding:main] Default flags will be empty.
08:50:27.629 INFO [n.f.f.Forwarding:main] Default flow matches set to: VLAN=true, MAC=true, IP=true, TPPT=true
08:50:27.629 INFO [n.f.f.Forwarding:main] Not flooding ARP packets. ARP flows will be inserted for known destinations
08:50:28.121 INFO [o.s.s.i.c.FallbackCCProvider:main] Cluster not yet configured; using fallback local configuration
08:50:28.121 INFO [o.s.s.i.SyncManager:main] [32767] Updating sync configuration ClusterConfig [allNodes={32767=Node [hostname=localhost, port=6642, nodeId=32767, domainId=32767]}, authScheme=CHALLENGE_RESPONSE, keyStorePath=/etc/floodlight/auth_credentials.jceks, keyStorePassword is unset]
08:50:28.389 INFO [o.s.s.i.r.RPCService:main] Listening for internal floodlight RPC on localhost/127.0.0.1:6642
08:50:28.552 INFO [n.f.c.i.OFSwitchManager:main] Listening for switch connections on 0.0.0.0/0.0.0.0:6653
08:50:28.635 INFO [n.f.l.i.LinkDiscoveryManager:main] Setting autoportfast feature to OFF
08

floodlight properties:
net.floodlightcontroller.core.internal.FloodlightProvider.openflowPort=6633

 Dan Tiernan Network Consultant 603-440-5704 


     On Tuesday, October 27, 2015 9:39 AM, Dan Tiernan <dtiernan@yahoo.com> wrote:
   

 Yes I can in about 45 minutes 
ThanksDan

Sent from my iPhone
On Oct 27, 2015, at 9:30 AM, Ryan Izard <notifications@github.com> wrote:


@dtiernan357 Can you please give the log at the beginning when you start the controller?Also, check to make sure you only have one controller running at a time.—

**Comment by rizard** [comment]
Do you have more than one of these lines in your properties file? I don't
have any problem changing the port number myself. Here's an example config
file I'm using for another project where I changed the port to 6699 -- it
works. Make sure the spelling of the variable string is exactly the same
for you and that you have not accidentally duplicated it. Also, please make
sure you save the file before running the controller (that's the only other
thing I can think of).

floodlight.modules=\

net.floodlightcontroller.jython.JythonDebugInterface,\

net.floodlightcontroller.storage.memory.MemoryStorageSource,\

net.floodlightcontroller.core.internal.FloodlightProvider,\

net.floodlightcontroller.threadpool.ThreadPool,\

net.floodlightcontroller.debugcounter.DebugCounterServiceImpl,\

net.floodlightcontroller.perfmon.PktInProcessingTime,\

net.floodlightcontroller.debugevent.DebugEventService,\

net.floodlightcontroller.staticflowentry.StaticFlowEntryPusher,\

net.floodlightcontroller.restserver.RestApiServer,\

net.floodlightcontroller.topology.TopologyManager,\

net.floodlightcontroller.forwarding.Forwarding,\

net.floodlightcontroller.linkdiscovery.internal.LinkDiscoveryManager,\

net.floodlightcontroller.ui.web.StaticWebRoutable,\

net.floodlightcontroller.loadbalancer.LoadBalancer,\

net.floodlightcontroller.firewall.Firewall,\

net.floodlightcontroller.devicemanager.internal.DeviceManagerImpl,\

net.floodlightcontroller.accesscontrollist.ACL

org.sdnplatform.sync.internal.SyncManager.authScheme=CHALLENGE_RESPONSE

org.sdnplatform.sync.internal.SyncManager.keyStorePath=/etc/floodlight
/auth_credentials.jceks

org.sdnplatform.sync.internal.SyncManager.dbPath=/var/lib/floodlight/

org.sdnplatform.sync.internal.SyncManager.port=6642

net.floodlightcontroller.forwarding.Forwarding.match=mac, ip, transport

net.floodlightcontroller.forwarding.Forwarding.flood-arp=YES

*net.floodlightcontroller.core.internal.FloodlightProvider.openflowPort=6699*

net.floodlightcontroller.core.internal.FloodlightProvider.role=ACTIVE

net.floodlightcontroller.linkdiscovery.internal.LinkDiscoveryManager.latency-history-size=
10

net.floodlightcontroller.linkdiscovery.internal.LinkDiscoveryManager.latency-update-threshold=
0.5

net.floodlightcontroller.core.internal.OFSwitchManager.defaultMaxTablesToReceiveTableMissFlow=
1

net.floodlightcontroller.core.internal.OFSwitchManager.maxTablesToReceiveTableMissFlowPerDpid=
{"00:00:00:00:00:00:00:01":"1","2":"1"}

net.floodlightcontroller.core.internal.OFSwitchManager.clearTablesOnInitialHandshakeAsMaster=
YES

net.floodlightcontroller.core.internal.OFSwitchManager.clearTablesOnEachTransitionToMaster=
YES

net.floodlightcontroller.core.internal.OFSwitchManager.keyStorePath=
/path/to/your/keystore-file.jks

net.floodlightcontroller.core.internal.OFSwitchManager.keyStorePassword=
your-keystore-password

net.floodlightcontroller.core.internal.OFSwitchManager.useSsl=NO

net.floodlightcontroller.core.internal.OFSwitchManager.supportedOpenFlowVersions=
1.0, 1.1, 1.2, 1.3, 1.4

net.floodlightcontroller.restserver.RestApiServer.keyStorePath=
/path/to/your/keystore-file.jks

net.floodlightcontroller.restserver.RestApiServer.keyStorePassword=your-
keystore-password

net.floodlightcontroller.restserver.RestApiServer.httpsNeedClientAuthentication=
NO

net.floodlightcontroller.restserver.RestApiServer.useHttps=NO

net.floodlightcontroller.restserver.RestApiServer.useHttp=YES

net.floodlightcontroller.restserver.RestApiServer.httpsPort=8081

net.floodlightcontroller.restserver.RestApiServer.httpPort=8080

Ryan Izard
Graduate Research/Teaching Assistant
306B Fluor Daniel Building
ECE Department, Clemson University
Clemson, SC 29634
rizard@g.clemson.edu
---------------------------------------------------
Big Switch Networks
ryan.izard@bigswitch.com

**Comment by dtiernan357** [comment]
Hi Ryan,
I have reinstalled the VM version 1.1 and confirm the properties files you sent. there was only two differences in my properties files.
   
   - net.floodlightcontroller.core.internal.OFSwitchManager.defaultMaxTablesToReceiveTableMissFlow=2  yours was 1
   - net.floodlightcontroller.forwarding.Forwarding.flood-arp=NO yours was yes
   - I assume you added the * at each end of the port listen line - is this correct

Question,
when you change the port listen on your device, in the debug screen did you see the 6699 under the line  INFO [n.f.c.i.OFSwitchManager:main] Listening for switch connections on 0.0.0.0/0.0.0.0:xxxx 
or is it still 6653?
any ideas?
dan

                          


 Dan Tiernan Network Consultant 603-440-5704

**Comment by rizard** [comment]
What asterisk? I don't have one on the port listen line.

Yes, I did see 6699 in place of xxxx in the debug screen.

Ryan Izard
Graduate Research/Teaching Assistant
306B Fluor Daniel Building
ECE Department, Clemson University
Clemson, SC 29634
rizard@g.clemson.edu
---------------------------------------------------
Big Switch Networks
ryan.izard@bigswitch.com

**Comment by dtiernan357** [comment]
this is what your entry looks like that you provided
*net.floodlightcontroller.core.internal.FloodlightProvider.openflowPort=6699*
That is why I asked?

How can i tell if the OF controller is up and running? 



 Dan Tiernan Network Consultant 603-440-5704

**Comment by rizard** [comment]
I don't see it like that. No there is no asterisk.

Ryan Izard
Graduate Research/Teaching Assistant
306B Fluor Daniel Building
ECE Department, Clemson University
Clemson, SC 29634
rizard@g.clemson.edu
---------------------------------------------------
Big Switch Networks
ryan.izard@bigswitch.com

**Comment by dtiernan357** [comment]
ok thanks,
It is painful to use floodlight.
Thanks again,dan

**Comment by rizard** [comment]
I'm sorry you feel that way. I really have no idea why your port
configuration is not taking effect. I would clone an entirely new
repository, edit just that file, save it, compile the code, and then run
it. The file should be parsed at run time, and the port should be opened on
the number you provide.

Could you be editing the wrong file? If you're like me and have a dozen or
so projects in different copies of the controller, you'll want to make sure
you aren't accidentally modifying the config file for a different copy of
the controller.

Ryan Izard
Graduate Research/Teaching Assistant
306B Fluor Daniel Building
ECE Department, Clemson University
Clemson, SC 29634
rizard@g.clemson.edu
---------------------------------------------------
Big Switch Networks
ryan.izard@bigswitch.com

**Comment by dtiernan357** [comment]
Hi Ryan,
I have tried several versions and yes you could be right in regards trying to get this to work. So, can you provide a link of the version of floodlight you think I should use? 

thanks for your continual support and guidance.
dan




 Dan Tiernan Network Consultant 603-440-5704

**Comment by rizard** [comment]
@dtiernan357 This should work in any version of Floodlight. What I'm saying is that if you have more than one instance of the Floodlight project on your computer, you might accidentally be editing the config file for say Floodlight copy A but you're running Floodlight copy B. Each copy would be in separate directories and have separate config files. Please make sure the config file is in the same Floodlight project copy as the JAR file you're running. You can verify this by running "pwd" in the terminal where you're editing the config file and where you're running the java command.

You can download a fresh copy from the master branch here: https://github.com/floodlight/floodlight

**Comment by dtiernan357** [comment]
Hi Ryan,
I am creating the floodlight controllers using VM and only have one version of Floodlight up and running at any given time.
I will download the floodlight version from the site you have provided. 

Stay tuned,
thanks,dan
 Dan Tiernan Network Consultant 603-440-5704

**Comment by raghdaaljaff** [comment]
Hello can somebody help me please Iam trying to implement the flowvisor in my floodlight controller and when I wrote this command sudo -u  flowvisor fvconfig generate /etc/flowvisor /config.json
The error is : sudo :unknown user:flowvisor
                        sudo :unable to initialize policy plugin.

**Comment by qingwang-bsn** [comment]
@soniekta these warnings should be safely ignored unless you want to enable a TLS/SSL OpenFlow channel. By default, Floodlight disable SSL and use normal OpenFlow channel.
