### ISSUE TITLE
LINK_TIMEOUT 

### ISSUE THREAD

**Issue by wenxueliu** [floodlight/floodlight#492]
LinkDiscoveryManager.java 770

`LINK_TIMEOUT` may be `1000 * LINK_TIMEOUT`,  otherwise the LINK_TIMEOUT will be 35 millseconds

**Comment by rizard** [comment]
I believe it's correct as-is. What that line is checking for is whether or not a reverse link has been added for a new link. For example, if a link from switch A port 1 to switch B port 2 was discovered, this block of code is checking to see if the reverse link from switch B port 2 to switch A port 1 was also discovered.

If the reverse link was not updated within the 35ms, then another LLDP packet is sent in the reverse direction to check if the link exists. All LLDP packets are flooded out all switches at the same time on a timer in the LinkDiscoveryManager, so chances are that the reverse link would have already been discovered. If this was 35ms*1000 = 35s, then that is a long time to wait to discover the reverse link in the case it was not discovered the first time. I suppose it would work, but I have a feeling 35ms is more reasonable for modern networks.

**Comment by rizard** [comment]
Same for this one here. Let us know if you still have any questions and open it up again if you feel it's not resolved.
