### ISSUE TITLE
staticflowentry bug

### ISSUE THREAD

**Issue by wenxueliu** [floodlight/floodlight#494]
the StaticFlowEntryPusher which implement IStaticFlowEntryPusherService, has some  consistence problems. the  `addFlow()` and `getFlows()` lack of consistence because  `addFlow()` only update storageSourceService without  entriesFromStorage.

**Comment by rizard** [comment]
@wenxueliu When addFlow() updates storageSourceService, it adds a row to the SFP table. The SFP is a listener for entries added/deleted/modified in the SFP table. The IStorageSourceListener rowsAdded() function gets called after the SFP adds the row, which then updates the SFP's local Maps, entiresFromStorage and entry2dpid.

**Comment by rizard** [comment]
I'm going to close this now to keep the issues list clean. Feel free to open it back up if you feel there is still an issue.
