### ISSUE TITLE
HARole bug?

### ISSUE THREAD

**Issue by wenxueliu** [floodlight/floodlight#498]
in the core/HARole.java the Constructor 
```
 HARole(OFControllerRole ofRole) {
    this.ofRole = ofRole;
}
```
can be same as 

static HARole ofOFRole(OFControllerRole role)  method.

**Comment by rizard** [comment]
@wenxueliu Why is this a bug?

**Comment by rizard** [comment]
@wenxueliu to keep the issues clean, I'm going to close this. If you feel there is a bug, please reopen.
