### ISSUE TITLE
question about the null pointer check and argment is emtpy check 

### ISSUE THREAD

**Issue by wenxueliu** [floodlight/floodlight#499]
I have a question about what the principle of floodlight which handle the null pointer and argment check because of I found a lot of methods exist this problem.

1. Don't check the all null pointer argment and developer make sure argment isn't null  if the method not receive user data, Only check the all null pointer argment of public method if the method receive user data.
2. if null pointer is passed,  catch the exception by upstream and decide by upstream

**Comment by wenxueliu** [comment]
Ｉ see somewhere use @Nullable and @Nonnull, is it recommended?

**Comment by rizard** [comment]
@wenxueliu nonnull is used to prevent people from calling a function with a null argument. It only works though (to my knowledge) if you directly supply a null value to the function with the nonnull annotation. If for example, if you call a function A with a null argument and it does not enforce nonnull, and A calls B, which does have the nonnull annotation, the compiler will not tell you there is an issue. It seems nonnull only works at a depth of 1.

So, there should be null checks in functions exposed in APIs. (Although, another way of thinking about it is that if you as a user supply a null value, and it's not supposed to be null, it's a error condition on your part, not on the function's your calling. Sure, the API should have a check -- to be nice, but it doesn't have to.) To prevent bugs though and to make the APIs easier to use, we want to include all null checks where necessary =)

If you find any parts of the code that should check for null (and throw an exception) but don't, please let us know where they are OR submit a pull request to the master branch fixing the issue. Also, please run all unit tests before submitting any pull requests.

**Comment by rizard** [comment]
@wenxueliu I fixed this a short while ago in a commit. Please reopen if you have any related issue. Thanks!
