### ISSUE TITLE
Floodlight : Bug in IDeviceListner

### ISSUE THREAD

**Issue by PragatiShrivastava** [floodlight/floodlight#515]
Hi!
I am developing a floodlight Module which implements IDeviceListner, "it is  listening  device moved event while device/host is not moving".(Error)
I m using Floodlight version 0.90, mininet and using LearningSwitch in place of Forwarding module.
I am creating topology in mininet and connecting it to my remote controller:
sudo mn --mac --controller=remote,ip=<controller ip>,port=6633 --switch ovsk
then my module prints the "device added+++" twice  i.e. number of host added in topology
but it also print "device moved"    once ,
Even when I am not making any changes to the topology, floodlight is calling deviceMoved method. 

public class Topo implements ITopologyListener, IFloodlightModule,

IDeviceListener {

protected ITopologyService topology;

    protected TopologyInstance instance = new TopologyInstance();

    protected IDeviceService deviceservice;

@Override

public void deviceAdded(IDevice device) {

// TODO Auto-generated method stub

System.out.println("Device added+++++++++++++++++++++++++++++++"+ device.getIPv4Addresses());

System.out.println(device.getMACAddress());

}

@Override

public void deviceRemoved(IDevice device) {

// TODO Auto-generated method stub

System.out.println("Device removed -----------------------------");

}

@Override

public void deviceMoved(IDevice device) {

// TODO Auto-generated method stub

System.out.println("Device moved -----------------------------");

System.out.println(device.getMACAddress());

}

@Override

public void deviceIPV4AddrChanged(IDevice device) {

// TODO Auto-generated method stub

}

@Override

public void deviceVlanChanged(IDevice device) {

// TODO Auto-generated method stub

}

@Override

public Collection<Class<? extends IFloodlightService>> getModuleServices() {

// TODO Auto-generated method stub

return null;

}

@Override

public Map<Class<? extends IFloodlightService>, IFloodlightService> getServiceImpls() {

// TODO Auto-generated method stub

return null;

}

@Override

public Collection<Class<? extends IFloodlightService>> getModuleDependencies() {

// TODO Auto-generated method stub

Collection<Class<? extends IFloodlightService>> l = new ArrayList<Class<? extends IFloodlightService>>();

    l.add(ITopologyService.class);

    l.add(IDeviceService.class);

    return l;

//return null;

}

@Override

public void init(FloodlightModuleContext context)

throws FloodlightModuleException {

// TODO Auto-generated method stub

topology=context.getServiceImpl(ITopologyService.class);

deviceservice =context.getServiceImpl(IDeviceService.class);

}

@Override

public void startUp(FloodlightModuleContext context) {

// TODO Auto-generated method stub

topology.addListener(this);

deviceservice.addListener(this);

}

@Override

public void topologyChanged() {

// TODO Auto-generated method stub

 

        System.out.println("topooooooooooooooooooooooo");
   }

}

**Comment by rizard** [comment]
@PragatiShrivastava I didn't realize you were using 0.90. There have been a lot of updates between that and 0.91 and between 0.91 and 1.0. Could you try 1.0?

**Comment by PragatiShrivastava** [comment]
Hi Ryan!
Yes that's correct, there is no issue with floodlight version 1.0 , but I
want to use

org.openflow.protocol.OFFlowRemoved;

org.openflow.protocol.OFMatch;

packages, those are not available in floodlight version 1.0. Implementation
of version 1.0 is very different from version 0.9. Can you help me to make
it easily understandable, please provide me some helpful resources.


Best Regards,

Pragati Shrivastava

**Comment by rizard** [comment]
Those have been replaced with other packages as a result of using the
Loxigen-generated library in lieu of the old JOpenFlow library.

Take a look here to see how to use Match in place of OFMatch and
OFFlowMod's OFFlowModify, OFFlowAdd, and OFFlowDelete (with strict
variations). OFFlowRemoved isn't discussed here, but it's in the same
package as OFFlowModify, etc.

https://floodlight.atlassian.net/wiki/display/floodlightcontroller/How+to+use+OpenFlowJ-Loxigen



Ryan Izard
Graduate Research/Teaching Assistant
306B Fluor Daniel Building
ECE Department, Clemson University
Clemson, SC 29634
rizard@g.clemson.edu
---------------------------------------------------
Big Switch Networks
ryan.izard@bigswitch.com

On Thu, Apr 9, 2015 at 1:42 PM, PragatiShrivastava <notifications@github.com

**Comment by rizard** [comment]
And take a look here for how I handle OFFlowRemoved:

https://github.com/floodlight/floodlight/blob/master/src/main/java/net/floodlightcontroller/staticflowentry/StaticFlowEntryPusher.java#L690

https://github.com/floodlight/floodlight/blob/master/src/main/java/net/floodlightcontroller/staticflowentry/StaticFlowEntryPusher.java#L778

Ryan Izard
Graduate Research/Teaching Assistant
306B Fluor Daniel Building
ECE Department, Clemson University
Clemson, SC 29634
rizard@g.clemson.edu
---------------------------------------------------
Big Switch Networks
ryan.izard@bigswitch.com

**Comment by PragatiShrivastava** [comment]
Thank you :)

**Comment by rizard** [comment]
@PragatiShrivastava You're welcome! Can this issue be considered closed then? Feel free to reach out on the mailing list again for any questions as you continue to develop.

**Comment by PragatiShrivastava** [comment]
Yes!
Now I am exploring floodlight version 1.0.
Thanks
