### ISSUE TITLE
loadbalancer module: only one BidirectionalVipRoutes

### ISSUE THREAD

**Issue by woniu17** [floodlight/floodlight#529]
I setup a topology with one switch connecting three hosts for testing module loadbalancer of floodlight.
One host(10.0.0.3) is as client and the other two(10.0.0.1, 10.0.0.2) are as members of pool-01(vip-01 10.0.0.200 is binded)
I try to use commond: curl http://10.0.0.200/index.html on 10.0.0.3 to get html page and it actually can get the page. The problem is that when using curl for one more time to get page, there are always 2 flow entries(one BidirectionalVipRoutes) on flow table, which SHOULD BE 2 MORE flow entries.
This is the flow entries when first curl:
```
cookie=0xa000000be7d0d7, duration=5.029s, table=0, n_packets=4, n_bytes=781, idle_age=3, tcp,in_port=2,nw_dst=10.0.0.3,tp_dst=43239 actions=mod_dl_src:12:34:56:78:90:12,mod_nw_src:10.0.0.200,output:3
cookie=*0xa00000de08a278*, duration=5.041s, table=0, n_packets=7, n_bytes=598, idle_age=3, tcp,in_port=3,nw_src=10.0.0.3,tp_src=43239 actions=mod_dl_dst:00:00:00:00:00:02,mod_nw_dst:10.0.0.2,output:2
```
And after second curl:
```
cookie=0xa000000be7d0d7, duration=6.372s, table=0, n_packets=4, n_bytes=781, idle_age=4, tcp,in_port=2,nw_dst=10.0.0.3,tp_dst=43240 actions=mod_dl_src:12:34:56:78:90:12,mod_nw_src:10.0.0.200,output:3
cookie=0xa00000de08a278, duration=6.376s, table=0, n_packets=7, n_bytes=598, idle_age=4, tcp,in_port=3,nw_src=10.0.0.3,tp_src=43240 actions=mod_dl_dst:00:00:00:00:00:02,mod_nw_dst:10.0.0.2,output:2
```
Moreover, Floodlight console output:
```
08:31:17.771 ERROR [n.f.s.StaticFlowEntryPusher:New I/O worker #12] Got a FlowRemove message for a infinite timeout flow: OFFlowRemovedVer13(xid=0, cookie=0x00a00000de08a278, priority=32768, reason=2, tableId=0x0, durationSec=13, durationNsec=24000000, idleTimeout=0, hardTimeout=0, packetCount=0x0000000000000007, byteCount=0x0000000000000256, match=OFMatchV3Ver13(in_port=3, eth_type=800, ip_proto=6, ipv4_src=10.0.0.3, tcp_src=43239)) from switch OFSwitchBase DPID[00:00:8e:0b:7f:6b:41:4a]
08:31:17.773 ERROR [n.f.s.StaticFlowEntryPusher:New I/O worker #12] Got a FlowRemove message for a infinite timeout flow: OFFlowRemovedVer13(xid=0, cookie=0x00a000000be7d0d7, priority=32768, reason=2, tableId=0x0, durationSec=13, durationNsec=16000000, idleTimeout=0, hardTimeout=0, packetCount=0x0000000000000004, byteCount=0x000000000000030d, match=OFMatchV3Ver13(in_port=2, eth_type=800, ip_proto=6, ipv4_dst=10.0.0.3, tcp_dst=43239)) from switch OFSwitchBase DPID[00:00:8e:0b:7f:6b:41:4a]
```

Is that ERRORs happen because the **cookie** of flow entry should be UNIQUE(two flow entries after first curl has the same cookies as the two after second curl)

Environment: Debian7.8, OVS 2.3.1, Floodlight master

**Comment by rizard** [comment]
@woniu17 The cookie isn't the problem. The cookie is just an ID you can give a flow to help you reference one or more flows more easily later. For example, the SFP uses a set cookie ID for all SFP flows that allow the SFP to detect when a flow it inserted was removed by the flow removed message.

The problem is that the LB is presently designed to balance between multiple source hosts between multiple destination hosts. If you use the same source again, the LB isn't presently smart enough to detect the difference. So, it removes the old flows and adds the new ones. 

This is an easy fix though I think. The string key the LB uses to identify flows in the SFP does not include the client source port as the name (only the target, which is 80 in both cases for you). If we include the source port too, it'll fix the problem methinks. What say you?

**Comment by woniu17** [comment]
Thanks! I mistook client.targetPort as the port the client used. I think if it would be understood well to make vipId followed by targetPort.
"inbound-vip-"+ member.vipId+"-client-"+client.ipAddress+"-port-"+client.targetPort+"-srcswitch-"+path.get(0).getNodeId()+"-sw-"+sw;
"inbound-vip-"+ member.vipId+"-port-"+client.targetPort+"-client-"+client.ipAddress+"-srcswitch-"+path.get(0).getNodeId()+"-sw-"+sw;

The LB will not work well if the same source simultaneously takes one more HTTP requests, which browser Firefox does. I think that is because the old flows are alternated by new flows again and again. Now I know it would be solved if I include the source port into SFP's entry name.

Thanks, again!

**Comment by rizard** [comment]
@woniu17 I agree. If you want to make the change and issue a pull request, the help would be appreciated! Make sure you run the unit tests afterwards to ensure nothing broke.

**Comment by rizard** [comment]
@woniu17 https://github.com/floodlight/floodlight/pull/592
