### ISSUE TITLE
Web UI Link Error

### ISSUE THREAD

**Issue by FatRabiTree** [floodlight/floodlight#530]
![ubuntu-floodlight-2015-04-29-12-10-05](https://cloud.githubusercontent.com/assets/8142547/7384728/5bcb2636-ee6b-11e4-8db8-3b1f32b36e7b.png)

If I click the link in footer, it can not lead me to the correct page, and the url in the browser is wrong.

**Comment by rizard** [comment]
@FatRabiTree Want to issue a pull request if you know the solution?

**Comment by FatRabiTree** [comment]
@rizard  I can give a try,but still studying the source code.

**Comment by rizard** [comment]
@FatRabiTree thanks! My time is divided between Floodlight and other things right now, but just reply back if you get stuck and I'll try and help out.

**Comment by FatRabiTree** [comment]
@rizard I sent a pull request, plz help to merge it. Thx a lot.
https://github.com/floodlight/floodlight/pull/534

**Comment by rizard** [comment]
@FatRabiTree I'll take a look first thing in the morning. Thanks!

Sent from my iPhone

--
Ryan Izard
Graduate Research/Teaching Assistant
306B Fluor Daniel Building
ECE Department, Clemson University
Clemson, SC 29634
rizard@g.clemson.edu
