### ISSUE TITLE
about ip-match with mask in StaticFlowPusher

### ISSUE THREAD

**Issue by woniu17** [floodlight/floodlight#538]
I'd like to modify some code on loadbalancer to make flows from a specify network (like 128.*.*.*) can go to the same member(server). So I set ip-match with mask using the following code:
 ```
Masked<IPv4Address> ipv4_dst = Masked.of(client.ipAddress, IPv4Address.of("255.0.0.0"));
mb.setExact(MatchField.ETH_TYPE, EthType.IPv4)
     .setMasked(MatchField.IPV4_DST, ipv4_dst)
      .setExact(MatchField.IP_PROTO, client.nw_proto)
```
It should get flow entries like these,
```
cookie=0x0, duration=6.649s, table=0, n_packets=4, n_bytes=592, tcp,in_port=1,nw_dst=128.0.0.0/8 actions=set_field:12:34:56:78:90:12->eth_src,set_field:10.0.0.200->ip_src,set_field:80->tcp_src,output:2
cookie=0x0, duration=6.658s, table=0, n_packets=6, n_bytes=488, tcp,in_port=2,nw_src=128.0.0.0/8 actions=set_field:00:00:00:00:00:02->eth_dst,set_field:10.0.0.2->ip_dst,set_field:80->tcp_dst,output:1
```
but the flow entries I got are,
```
cookie=0x12345678, duration=6.254s, table=0, n_packets=0, n_bytes=0, send_flow_rem tcp,in_port=1,nw_dst=128.0.0.0 actions=set_field:12:34:56:78:90:12->eth_src,set_field:10.0.0.200->ip_src,set_field:80->tcp_src,output:2
cookie=0x12345678, duration=6.277s, table=0, n_packets=0, n_bytes=0, send_flow_rem tcp,in_port=2,nw_src=128.0.0.0 actions=set_field:00:00:00:00:00:02->eth_dst,set_field:10.0.0.2->ip_dst,set_field:80->tcp_dst,output:1
```
loadbalancer use staticflowpusher to write flows to switches. I think there is some problem on staticflowpusher, because when I change code on loadbalancer 
```
switchService.getSwitch(sw).write(fmb.build());
//sfpService.addFlow(entryName, fmb.build(), sw);
```
It works like I want, and get flow entries:
```
cookie=0x0, duration=6.649s, table=0, n_packets=4, n_bytes=592, tcp,in_port=1,nw_dst=128.0.0.0/8 actions=set_field:12:34:56:78:90:12->eth_src,set_field:10.0.0.200->ip_src,set_field:80->tcp_src,output:2
cookie=0x0, duration=6.658s, table=0, n_packets=6, n_bytes=488, tcp,in_port=2,nw_src=128.0.0.0/8 actions=set_field:00:00:00:00:00:02->eth_dst,set_field:10.0.0.2->ip_dst,set_field:80->tcp_dst,output:1
```

Environment: Debian7.8, OVS 2.3.1, Floodlight master

**Comment by rizard** [comment]
@woniu17 

I see the problem and will push a patch shortly.

Thanks for pointing this out!

**Comment by rizard** [comment]
@woniu17 Can you test my master branch? Please let me know if that solves your problem.
It's here:

http://github.com/rizard/floodlight/tree/master

**Comment by woniu17** [comment]
Yes, it's my pleasure. Do I just check if that solves my problem? Or if I need to run some unit tests? I am not so familiar with unit test. :(

**Comment by rizard** [comment]
Just check and see if it solves your problem. It already passes tests.

Ryan Izard
Graduate Research/Teaching Assistant
306B Fluor Daniel Building
ECE Department, Clemson University
Clemson, SC 29634
rizard@g.clemson.edu
---------------------------------------------------
Big Switch Networks
ryan.izard@bigswitch.com

**Comment by woniu17** [comment]
OK, I will response you as soon as possible.

It will be fantastic!

**Comment by woniu17** [comment]
@rizard I'd like to use the feature of IP-bitmask, I think it works well in SFP now. 
Thanks!

**Comment by rizard** [comment]
Great! Let us know if you run into any other issues!

Sent from my iPhone

--
Ryan Izard
Graduate Research/Teaching Assistant
306B Fluor Daniel Building
ECE Department, Clemson University
Clemson, SC 29634
rizard@g.clemson.edu
