### ISSUE TITLE
Maven integration

### ISSUE THREAD

**Issue by oxisto** [floodlight/floodlight#541]
Hi everyone,

is there a plan to support maven through a pom.xml or even putting it on a maven repo like OpenFlowJ? It would greatly improve the development of third party modules.

I actually have written a dummy pom-file (see commit https://github.com/oxisto/floodlight/commit/9920832a5fdb91b7894ee08f2922bede521b9db5) to support the development of our own modules. However, there are currently some issues:
* Versions of libraries probably do not match the supplied libs 100% at the moment
* Tests are disabled temporarily because of unexpected test failures.

Let me know if it is worth fixing those things and creating a pull request, otherwise i'll just keep it for own internal toolchain.

Cheers,

Christian

**Comment by rizard** [comment]
@oxisto 
Hi Christian,

There is a desire to support it, but not a concrete plan. If you would like integrate maven, that would be appreciated! Personally, I don't have much experience with it and have prioritized other items ahead of it, which is the reason we don't support it yet. That's not a good reason to not support it though ;)

As for the test failures, in some unit tests, there are unintentional dependencies, where if the tests are not run in the correct order, they will fail. Obviously, this is not a feature and rather a bug. It's something that I've been meaning to fix. If you're particularly skilled with Java unit tests, then please feel free to poke around. That's most likely the issue you're observing.

Thanks for your extensive help on the mailing list recently and with your contributions! Your help is greatly appreciated!

Ryan

**Comment by oxisto** [comment]
I'll have a look if there is an "easy" fix for the test dependencies, otherwise i can upload a pom.xml with tests disabled for now.

**Comment by rizard** [comment]
@oxisto I found and fixed one dependency bug. The pull request was just merged now with master. Let me know if that fixes the failed unit tests you are seeing.

**Comment by oxisto** [comment]
I've opened the pull request, I still have four test failures (i also have those test failures with ant btw) so i kept the tests disabled. I'll try to investigate the test failures further.

**Comment by rizard** [comment]
@oxisto I've merged the pull request. As noted in my comment in #546, I'll test to make sure the new versions of RESTlet and Netty do not cause any issues with SSL OpenFlow connections and HTTPS via the REST API. Thanks!
