### ISSUE TITLE
Unit test failures

### ISSUE THREAD

**Issue by oxisto** [floodlight/floodlight#548]
I'm opening this issue to keep track of failed unit tests. I know that my pull request broke one test for sure, but the rest seemed to fail even before that. Two test failures were fixed by an earlier commit from rizard.

Current failures (running ant tests):

Test Class | Test Method | Issue | Solution
-------- | -------- | -------- | --------
net.floodlightcontroller.core.OFSwitchBaseTest | testValidLogicalOFMessageCategory | This was caused by #542 | I need to tell easymock to expect the call to handleOutgoingMessage. A fix is currently being prepared 
net.floodlightcontroller.core.internal.OFSwitchHandlerTestBase | all | This class is actually an abstract class and basis for further tests (that are executed correctly), ant should never actually try to execute it directly | Probably needs patching in build.xml?
net.floodlightcontroller.staticflowentry.StaticFlowTests | testStaticFlowPush | Mismatch in the OF match | ?
net.floodlightcontroller.test.FloodlightTestCase | all | Caused an ERROR: No runnable methods | Class contains no test methods, remove or exclude
net.floodlightcontroller.util.FutureTestUtils | all | see above | Remove or exclude from tests

**Comment by oxisto** [comment]
Interestingly enough, if i run the tests in eclipse, e.g. right-click on src/test/java -> run unit tests, all the tests run fine with my first hotfix applied. It seems eclipse automatically excludes those 3 classes that contain no real tests.

However, the testStaticFlowPush is failing in ant and succeeding in eclipse. This seems to be another dependency issue.

**Comment by oxisto** [comment]
With the code in pull request #549, all tests are running fine in maven now, so i re-enabled the tests in the pom.xml. Maybe someone else can look into issues with ant - since i don't really have much experience there.

**Comment by rizard** [comment]
@oxisto I've finding some dependency issues in the tests now. For some reason or another, some have more than one Before annotation where the second Before method expects the first Before method to have been run first. But, there is no guarantee in the ordering except that all Before annotated methods will be run before all Test annotated methods, followed by all After annotated methods.

I'm fixing these where I find them right now. I'll look into the ant issues you pointed out above. Thanks!

**Comment by rizard** [comment]
@oxisto Thanks for the insight, which confirmed my observations as well. The ant tests are passing, so I'll close this issue. Many thanks!

**Comment by oxisto** [comment]
I've found one more issue with the SyncManager tests. These fail under some weird circumstances (e.g. if i'm connected via VPN). I didn't look into the details but it looks like the test is using my VPN ip address to connect to the local sync manager server. It could be a very specific issue with our cisco VPN adapter because the tests compile fine if i'm connected to any other network directly.
