### ISSUE TITLE
About details of flow entry in index.html

### ISSUE THREAD

**Issue by nameagain** [floodlight/floodlight#556]
Is it a good idea to show the flow name on the webpage?
Because we have to delete flows with flow names but flow names do not appear in the web ui and dump-flows command.

**Comment by rizard** [comment]
@nameagain Flows do not have names outside the context of the Static Flow Pusher, which associates a flow with a name key in a map. The flows shown in the webpage are the result of a flow stats query to the switch. Any and all flows on the switch will be displayed there, even flows not inserted by the SFP that don't have names.

**Comment by rizard** [comment]
@nameagain I'm going to close this to keep the list of active issues clean. Please feel free to reopen or contact the developer's list at floodlight-dev@openflowhub.org if you have any other questions!
