### ISSUE TITLE
Getting some help in forwarding

### ISSUE THREAD

**Issue by Hesam-Naderi-Dehkordi** [floodlight/floodlight#564]
Hi everybody. I 'm a MS student in networking course and my project is based on using of an IDS and Floodlight.
I have read the REST API tutorial but didn't find how to implement my work.
Some part of my project is that I need that the traffic will be send to the IDS before sending to the real destination and if the the traffic is clean , a reply will be sent back by IDS to the controller so controller forward the packet to real destination; else the traffic will be dropped.
Can any body help me in how to do this, which APIs, classes or files to be deal with?
Any helps or solutions will be welcomed.
Many thanks in advance.

**Comment by rizard** [comment]
@Hesam-Naderi-Dehkordi 

Sounds like a cool project! Please address your question to the mailing list at floodlight-dev@openflowhub.org. You will have a greater outreach there, and we try to reserve GitHub issues for code problems / bug reports rather than how-to questions =)
