### ISSUE TITLE
Download links on your website dont work

### ISSUE THREAD

**Issue by jamiephillips0000** [floodlight/floodlight#573]
Hi 
I am pretty sure this is not the place to put this but you don't have any details to make contact on your website - apologies for this
Links to download floodlight do not work e.g. http://floodlight-download.projectfloodlight.org/files/floodlight-source-0.90.zip

Jamie

**Comment by rizard** [comment]
@jamiephillips0000 which website is that link on? That's outdated, and all code should be downloaded directly from GitHub using the branch/version you want.

**Comment by jamiephillips0000** [comment]
Hi Ryan
1) The website is http://www.projectfloodlight.org/download/
2) I am installing Open Mano (https://github.com/nfvlabs/openmano) and part of that seems to use floodlight 0.90.
2) The installation instructions are as follows
    wget https://github.com/nfvlabs/openmano/raw/master/scripts/install-openmano.sh
    chmod +x install-openmano.sh 
    sudo ./install-openmano.sh root adminuser
3) The file install-openmano.sh tries to download http://floodlight-download.projectfloodlight.org/files/floodlight-source-0.90.zip and this fails with a timeout
4) I am aware it is an older version - I just thought you might be interested that the link does not work for that version or a couple of the other versions

Kr
Jamie

**Comment by rizard** [comment]
That is an old website the script is using. We've moved to a new site, and
we're using GitHub as the place to host all our code. You can modify the
download link to the following:

https://github.com/floodlight/floodlight/archive/v0.90.zip

Ryan Izard
Graduate Research/Teaching Assistant
306B Fluor Daniel Building
ECE Department, Clemson University
Clemson, SC 29634
rizard@g.clemson.edu
---------------------------------------------------
Big Switch Networks
ryan.izard@bigswitch.com

**Comment by rizard** [comment]
@jamiephillips0000 Thanks for the update. Feel free to reopen this issue if you need to.
