### ISSUE TITLE
Improve the Web UI request by changing ajax to websocket

### ISSUE THREAD

**Issue by FatRabiTree** [floodlight/floodlight#578]
websocket is proved to be more efficient in getting data. I believed that some UI laggy problem can be fixed through this improvement.

**Comment by rizard** [comment]
@FatRabiTree Would you like to issue a pull request with the changes you're recommending?

**Comment by FatRabiTree** [comment]
I'll give a try

**Comment by rizard** [comment]
@FatRabiTree Any updates here?

**Comment by rizard** [comment]
@FatRabiTree We're about to roll out a new web UI. This will be irrelevant soon, so I'll close it now.
