### ISSUE TITLE
Static Flow Pusher returns 200 when "switch" property is not present in the given flow

### ISSUE THREAD

**Issue by chechoRP** [floodlight/floodlight#587]
Given a flow that does not have the required *"switch"* property/value, the SFP will return *200, 'OK', '{"status" : "Entry pushed"}')* when in fact the entry wasn't installed. Instead, the output should be something with error code +400 and a message of invalid flow configuration. 

Flow used:
```
{"eth_dst": "02:2c:9c:e9:46:b9","eth_src": "02:42:84:37:b9:70", 
"name": "fl-flow___s1", "hard_timeout": "0", 
"actions": "output=controller,set_ipv4_src=10.10.1.2,set_ipv4_dst=10.10.2.2,output=ingress-port,set_tp_dst=74,output=local",
 "priority": "65535", "ip_proto": "0x11", 
"idle_timeout": "0", "eth_type": "0x800", "ipv4_src": "10.10.3.1", 
"active": "true", "udp_dst": 50
}
```

Discussion in mailing-list: https://groups.google.com/a/openflowhub.org/forum/#!topic/floodlight-dev/OEvPYUWnjuQ

**Comment by rizard** [comment]
@chechoRP Sorry for taking forever on such a simple fix. It should be addressed by this patch here:

https://github.com/floodlight/floodlight/pull/603

We really should have a more robust flow checking system (at least with an enum instead of ints...)
