### ISSUE TITLE
OFMeta.class toString()  causes bug in Static Flow Pusher

### ISSUE THREAD

**Issue by mindi102680** [floodlight/floodlight#591]
I use     sfpService.addFlow( flowName,fmb.build(), swDPID)    to push a flow matches metadata

it calls flowModToStorageEntry
( Line 144 of StaticFlowEntries.java)

in Line 560 & 562, it calls 
match.get(MatchField.METADATA).toString()
match.getMasked(MatchField.METADATA).toString()

it set metadata to  "Metadata: " + u64.toString();

558    case METADATA:
559        if (match.supports(MatchField.METADATA) && match.isExact(MatchField.METADATA)) {
560            entry.put(StaticFlowEntryPusher.COLUMN_METADATA, match.get(MatchField.METADATA).toString());
561        } else if (match.supportsMasked(MatchField.METADATA) && match.isPartiallyMasked(MatchField.METADATA)) {
562           entry.put(StaticFlowEntryPusher.COLUMN_METADATA, match.getMasked(MatchField.METADATA).toString());
563        } else {
564           log.error("Got match for {} but protocol {} does not support said match. Ignoring match.", 565               StaticFlowEntryPusher.COLUMN_METADATA, match.getVersion().toString());
566        }
567        break;

in       org.projectfloodlight.openflow.types.OFMetadata

67    @Override
68    public String  toString() {
69        return "Metadata: " + u64.toString();
70    }

and then triggered a NumberFormatException  in   StaticFlowEnryPusher.java
    fmb.setMatch(MatchUtils.fromString(match, fmb.getVersion()));

because the matchField of metata data has been changed into  "Metadata: " + u64.toString();
by  flowModToStorageEntry  in StaticFlowEntries.java

when I use restAPI of StaticFlowPusher, 
it works well,
but the Entry shows on webUI
the matchfield shows metadata=Metadata:0xxx1

so I wonder if it's better to change the toString() function of
org.projectfloodlight.openflow.types.OFMetadata
into

67    @Override
68    public String  toString() {
69        return u64.toString();
70    }

then the problem of Entry shows on webUI and  NumberFormatException  can be solved.

**Comment by FatRabiTree** [comment]
this bug could make the metadata field in openflow switch an error because it's redundant string "Metadata: ", right?

**Comment by rizard** [comment]
@mindi102680 @FatRabiTree 

This should probably be fixed in our Loxi library (http://github.com/floodlight/loxigen). The toString() of Loxi-defined types should just include the number (and a leading "0x" if it's hex). If it includes the string "metadata" in front of it, then we should remove it there. You can open an issue for Loxi or even better fix and issue a pull request if you're familiar with how Loxi works.

Thanks for pointing this out!

**Comment by rizard** [comment]
@FatRabiTree @mindi102680 

https://github.com/floodlight/loxigen/pull/427
