### ISSUE TITLE
Forwarding Issue:

### ISSUE THREAD

**Issue by rickphd** [floodlight/floodlight#596]
"doFlood" function of "Forwarding" module uses:
Set<OFPort> broadcastPorts = this.topologyService.getSwitchBroadcastPorts(sw.getId());
But "broadcastPorts" always is null and therefore the flooding process for ARP request is never done.

The responsible of return the "broadcastPorts" is the "calculateBroadcastPortMap()" function of "TopologyInstance" module.  It seems that this functions is not working properly since it returns nothing.

**Comment by rizard** [comment]
@rickphd When is it null for you? After the topology is discovered (a prerequisite for Forwarding), the list should contain a list of ports. Are you allowing enough time for the controller to learn your topology before ARPing? What is your topology?

**Comment by rizard** [comment]
@rickphd Actually, if your topology consists of completely isolated switches, or just one switch, then this will return null when in fact it should return FLOOD. Is that your situation?

It appears that is an edge case we didn't consider. If there are no links present in an OpenFlow island (meaning it's just a single switch by itself), then trees cannot be computed. In this case, we just need to all all the switch's ports as broadcast ports.

**Comment by rizard** [comment]
@rickphd Does this help? https://github.com/floodlight/floodlight/pull/598

**Comment by rickphd** [comment]
Thanks for you reply rizard.
Yes, my topology consists of just one switch. So, what I have to do next?, I don't understand the last part of your message ("we just need to all all the switch's ports as......)
Thanks in advance.

**Comment by rizard** [comment]
@rickphd Can you try a new copy of the master branch? I updated it to (I think) address the problem you discovered.

Thanks,

Ryan

**Comment by rickphd** [comment]
Hi Ryan,
I executed "git clone git://github.com/floodlight/floodlight.git " to get a new copy but the result is the same: "broadcastPorts" is null.
My last test was quite simple: two host connected throught one OVS.
I would appreciate your help.
Thanks.

**Comment by rizard** [comment]
@rickphd How about now?
I created your same topology and replicated the issue. It should be fixed in this pull request I just merged: https://github.com/floodlight/floodlight/pull/599

Please follow up and let me know if this resolves your problem. Thanks for your patience!

**Comment by rickphd** [comment]
Hi Ryan,
It works!.
Thank you so much for your time.
Regards.
Rick.

**Comment by rizard** [comment]
@rickphd Awesome! I'll close this issue then. Feel free to reopen it if you run into the same problem again. If you have any general questions, please reach out on our developer mailing list at floodlight-dev@openflowhub.org
