### ISSUE TITLE
Double Tagging Vlan Id Issue OFBadActionErrorMsgVer13(xid=1700, code=BAD_ARGUMENT

### ISSUE THREAD

**Issue by kharegaurav75** [floodlight/floodlight#600]
Hi 
I need to generate the double Vlan tag and install the flow rules in IPv4 such that when packet comes to the switch , switch will add the double Vlan tag in the Packet header.

We have tried the below combination of below EthType  value.
EthType.IPv4 and EthType.VLAN_FRAME for Inner Tag.
EthType.BRIDGING and EthType.Q_IN_Q for Outer Tag.

But we are getting  Exception :- OFBadActionErrorMsgVer13(xid=1700, code=BAD_ARGUMENT,  
Could you please suggest 
1.  value for Inner and outer Vlan tag for IP4 (TCP) packets?
2. some steps or tutorial for vlan tag?

1. Code:-

ArrayList<OFAction> vlan_action = new ArrayList<OFAction>();
OFFlowAdd flowAdd ;
//Inner Tag
OFVlanVidMatch ofvlanInner = OFVlanVidMatch.ofVlan(2);
vlan_action.add( new OFActionsVer13().pushVlan(EthType.VLAN_FRAME) );
vlan_action.add( actions.buildSetField().setField( oxms.vlanVid(ofvlanInner) ).build() );
//Outer tag			
OFVlanVidMatch ofvlanOuter = OFVlanVidMatch.ofVlan(1);
vlan_action.add( new OFActionsVer13().pushVlan(EthType.Q_IN_Q) );
vlan_action.add( actions.buildSetField().setField( oxms.vlanVid(ofvlanOuter) ).build() );
		
OFActionOutput output = actions.buildOutput()
    .setMaxLen(0xFFffFFff)
    .setPort(OFPort.of(2))
    .build();
 vlan_action.add(output);
				
flowAdd = offFactory.buildFlowAdd()
	    .setBufferId(OFBufferId.NO_BUFFER)
	    .setHardTimeout(3600)
	    .setIdleTimeout(10)
	    .setPriority(32768)
	    .setActions(vlan_action)
	    .setMatch(match)
	    .setOutPort( OFPort.ofInt(2) )
	    .build() ;
			
	sw.write( flowAdd );

**Comment by rizard** [comment]
@kharegaurav75 Are you the folks who were mailing the developers list about this issue?

If you're using OVS, I don't *believe* OVS supports double tagging (QinQ).

**Comment by kharegaurav75** [comment]
Hi Ryan
i had opened the issue.
Now, I have closed the issue as the  switch does not support the double
tagging functionality

Thanks
Gaurav
