### ISSUE TITLE
problem with vlan in openvswitch with floodlight controller

### ISSUE THREAD

**Issue by gang929** [floodlight/floodlight#604]
I create a network  with a physic host install ovs and two vm, the VM1 is set vlan 100, the vm2 is set vlan 200 ,like this
         physic Host1: open-vswitch (br1)                           　　     physic host2: floodlight
                  　　             　     　　 |
                  　　             /            　　           　　                  　　      \
 VM1 (vlan 100)                      　　  VM2(vlan 200)
physic Host1  br1: 10.0.111.111
vm1 ip: 192.168.100.100  vlan:100
vm2 ip: 192.168.100.200  vlan:200
physic Host2: 10.0.111.112
in this case, vm1 can not ping vm2.

when i set the open-vswithc's controller with floodlight
ovs-vsctl set-controller br1 tcp:10.0.111.112:6653
the  vm1 can ping vm2.

floodlight start with default floodlightdefault.properties

floodlight not implement vlan check?  how can i config floogligth with vlan?

**Comment by rizard** [comment]
@gang929 Did you ask this question on the mailing list already? It looks familiar.

If so, let me know if we helped you resolve your problem so that this can be closed.

If this is different, let me know too and I'll take a look.

**Comment by gang929** [comment]
@rizard you are right!
the question  can be close
I found the resaon at https://github.com/openvswitch/ovs/blob/master/FAQ.md#q-my-openflow-controller-doesnt-see-the-vlans-that-i-expect.

**Comment by gang929** [comment]
@rizard
I modify ForwardingBase.java like below,  the  VM1 (vlan 100) 　can not print　 VM2(vlan 200).
this method is right?
-------------------------------------------------------------
Index: ForwardingBase.java
===================================================================
--- ForwardingBase.java	(版本 2273)
+++ ForwardingBase.java	(工作副本)
@@ -261,7 +261,7 @@
 			OFPort outPort = switchPortList.get(indx).getPortId();
 			OFPort inPort = switchPortList.get(indx - 1).getPortId();
 			mb.setExact(MatchField.IN_PORT, inPort);
-			aob.setPort(outPort);
+			aob.setPort(OFPort.NORMAL);//(outPort);
 			aob.setMaxLen(Integer.MAX_VALUE);
 			actions.add(aob.build());
 			
@@ -272,7 +272,7 @@
 			.setHardTimeout(FLOWMOD_DEFAULT_HARD_TIMEOUT)
 			.setBufferId(OFBufferId.NO_BUFFER)
 			.setCookie(cookie)
-			.setOutPort(outPort)
+			.setOutPort(OFPort.NORMAL)//(outPort)
 			.setPriority(FLOWMOD_DEFAULT_PRIORITY);
 
 			try {

**Comment by rizard** [comment]
@gang929 Why are you using the outPort computed and NORMAL?

**Comment by gang929** [comment]
@rizard   when ovs has not set controller,  the VM1 (vlan 100) 　can not print　 VM2(vlan 200). this is right!  it is expect with vlan.
when ovs set controller with floodlight,  the VM1 (vlan 100) 　can  print　 VM2(vlan 200), but  VM1 (vlan 100) should not print　 VM2(vlan 200), the reason is https://github.com/openvswitch/ovs/blob/master/FAQ.md#q-my-openflow-controller-doesnt-see-the-vlans-that-i-expect.
so, I modify  pushroute method in  ForwardingBase.java , when write flow , the old action is output:x,  i modify  the action to normal, the result flow in ovs is action be write normal!  in this case,  the VM1 (vlan 100) 　can not print　 VM2(vlan 200), but  the VM1 (vlan 100) 　can not print　 VM3(vlan 100),  it is expect with vlan.

**Comment by rizard** [comment]
@gang929 That makes sense. Thanks!

I'll close this issue then. Feel free to ask the developer group if you have any issues. Or you can also open this issue again or make a new one if it's a bug in our code.
