### ISSUE TITLE
Live Update feature doesn't work

### ISSUE THREAD

**Issue by Hesam-Naderi-Dehkordi** [floodlight/floodlight#607]
Hi.
Using the master branch (26 November 2015) live update feature doesn't work.
Tried with Firefox,Chromium,Konquer and no difference.

**Comment by rizard** [comment]
@Hesam-Naderi-Dehkordi This worked for me yesterday. I observed the REST API of Floodlight being periodically queried by the web page's live update JS code.

Is there a specific live update field/data-set that is not being updated?

**Comment by Hesam-Naderi-Dehkordi** [comment]
yes, you can see in the floodlight logging that periodical queries, but nothings get updated on the webpage and not reflecting the changes

**Comment by rizard** [comment]
@Hesam-Naderi-Dehkordi can you inspect the webpage while it's running to see if there are any errors occurring?

**Comment by benboy-han** [comment]
Dear friend,
   Firstly, thank you very much.we have solved all problem.Thank you.If we have problem can not be solved, we can communicate!

**Comment by rizard** [comment]
@benboy-han @Hesam-Naderi-Dehkordi Glad to hear you solved the problem! We're going to roll out a new web UI in the future. It would help us if you could tell us about any issues you'd like resolved or any features added to floodlight-dev@openflowhub.org.
