### ISSUE TITLE
devicemanger problem

### ISSUE THREAD

**Issue by wenxueliu** [floodlight/floodlight#643]
1. the device update should be pub-sub pattern.
2. Is IEntityClass , IEntityClassifierService and IEntityClassListener is  redundance,  a map between  deviceKey and entity  is perfer ?

**Comment by rizard** [comment]
@wenxueliu Can you elaborate please on what the problem is? I don't quite understand. Thanks!

**Comment by rizard** [comment]
@wenxueliu I'm going to close this issue to keep our list of active issues clean. Please re-open or discuss what you think the problem is on floodlight-dev@openflowhub.org.
