### ISSUE TITLE
use IOFSwitchService throw null exception

### ISSUE THREAD

**Issue by WarEric** [floodlight/floodlight#648]
##  It throws a null pointer Exception when I use getModuleDependencies() to obtain a IOFSwitchService .
    
   **The OFSwitchManager throws a null pointer Exception at this.switchListener=null and I don't know why.**
    	
```
   @Override
   public void addOFSwitchListener(IOFSwitchListener listener) {
	this.switchListeners.add(listener);
}
```

  **The problem solved when I find add IOFSwitchService and IFloodlightProviderService together in getModuleDependencies() by accident . Eventually I use  IOFSwitchService singlely in getModuleDependencies() and the problem disappeared.**
* first

```
   @Override
    public Collection<Class<? extends IFloodlightService>> getModuleDependencies() {
        Collection<Class<? extends IFloodlightService>> l=new ArrayList<Class<? extends IFloodlightService>>();
        l.add(IFloodlightProviderService.class);
        l.add(IOFSwitchService.class);
        return l;
    }
```
    
* second

```
@Override
    public Collection<Class<? extends IFloodlightService>> getModuleDependencies() {
        Collection<Class<? extends IFloodlightService>> l=new ArrayList<Class<? extends IFloodlightService>>();
        l.add(IOFSwitchService.class);
        return l;
    }
```

**I don't know why because the official documentation never say that I have to use two Service together and there is a association using them.(By the way, I am a college student. )**

**Comment by rizard** [comment]
@WarEric You must first depend on IOFSwitchService before you can add yourself as a listener. This will allow you to get a reference to IOFSwitchService in your module's init() function. In startup(), you can add yourself as a listener.

**Comment by rizard** [comment]
@WarEric to keep our issues clean, I'm going to close this for now. Feel free to send an email to floodlight-dev@openflowhub.org if you have any questions going forward.
