### ISSUE TITLE
Firewall rules do not work when forwarding module is closed.

### ISSUE THREAD

**Issue by lanskytian** [floodlight/floodlight#664]
Even though adding rules in firewall, it does not work when I closed Forwarding module. 
I wonder IF FIREWALL DOES NOT WORK WHEN FORWARDING MODULE IS CLOSED?
thx.

**Comment by rizard** [comment]
@lanskytian the firewall must operate with the forwarding module enabled. What happens is the firewall looks at the packet-in headers and makes a routing decision. The forwarding module then enacts the decision by either allowing or denying the packet. Allows are implemented by flows that forward packets. Denies are implemented with a flow that has no output actions (i.e. drop).
