### ISSUE TITLE
Request: openflowj-loxi update in next major Floodlight release?

### ISSUE THREAD

**Issue by rsharo** [floodlight/floodlight#685]
@rizard I know there is a major Floodlight release coming up shortly (v1.3?).

Not asking for any promises... but can you update to the latest openflowj-loxi when you push the release?  I'd like to be able to use the code from [Loxigen PR 503](https://github.com/floodlight/loxigen/pull/503) and [Loxigen PR 505](https://github.com/floodlight/loxigen/pull/505)  if they are merged by the time you start the release process.

Thanks,
   rsharo

**Comment by rizard** [comment]
@rsharo we're working on v2.0 given the many API changes. One big change will be removing ant support and using only maven. Maven will automatically fetch the latest OpenFlowJ-3.0.0-SNAPSHOT in v2.0 of Floodlight when you run mvn install. Master branch does this already.

**Comment by rsharo** [comment]
@rizard Thanks!
