### ISSUE TITLE
Host to switch links has not shown in Web Ui  (floodlight v1.2)

### ISSUE THREAD

**Issue by hmd1st** [floodlight/floodlight#704]
I ran a topology for testing multipath routing after recent commits on floodlight repo.
In mininet, the topology has built correctly as I am able to ping between h1 and h2.
my topology is like this:
![image](https://cloud.githubusercontent.com/assets/7472777/18087257/7bf92be4-6ec9-11e6-9e36-8fc900503ffb.png)
Links h1 to s1 and h2 to s5 has not shown. I don`t know why ?

I use ubuntu 14.04 and firefox 48.0 browser(I checked that on chrome v50 and the problem still exists).
 and this is my mininet script:

[multipathtest.py.gz](https://github.com/floodlight/floodlight/files/445903/multipathtest.py.gz)

**Comment by cbarrin** [comment]
Thanks for all the helpful information! I just issued a pull request for the UI, so it should be fixed within the hour.

**Comment by rizard** [comment]
@hmd1st, fixed by @cbarrin https://github.com/floodlight/floodlight/pull/706
