### ISSUE TITLE
Host to Switch Links do not display in webUI

### ISSUE THREAD

**Issue by sandaruwanjayaweera** [floodlight/floodlight#705]
Hi everyone,
I am using Ubuntu 14.04 LTS, Mozilla Firefox web browser 48.0, floodlight v1.2 and mininet 2.2.1. I am trying to run a tree topology with depth=2 and fanout=2. When I try to view the topology using the webUI, it does not display the links between hosts and switches.
This is the command I used,
**sudo mn --controller=remote,ip=127.0.0.1,port=6653 --topo tree,depth=2,fanout=2**

![floodlight2](https://cloud.githubusercontent.com/assets/20835867/18087948/4f9193d2-6ed5-11e6-9c61-22520e263a7e.png)

I have tried both master and v1.2 in floodlight. I used both Mozilla Firefox web browser and Google Chrome web browser.

**Comment by rizard** [comment]
@sandaruwanjayaweera fixed https://github.com/floodlight/floodlight/pull/706

**Comment by sandaruwanjayaweera** [comment]
Wow. Thank you @cbarrin <https://github.com/cbarrin> and *rizard
<https://github.com/rizard>* for your quick response.
