### ISSUE TITLE
staticentrypusher doesn't check duplicate flows

### ISSUE THREAD

**Issue by allewwaly** [floodlight/floodlight#736]
When the staticentrypusher api (/wm/staticentrypusher/json) insert a flow to storage, it doesn't check duplicate flows. Currently it only check if the name exists, however, some flows with different names are actual identical flows with the same matching field, priority and actions.  This also causes the staticentryspusher list (/wm/staticentrypusher/list/all/json) api returns multiple identical flows with only names different. 

I think the problems comes from MemoryStorageSource.java --> insertRows function. Besides of name, I suggest adding flow checking logic here to avoid duplicate flows from being repeatedly inserted.

**Comment by allewwaly** [comment]
Besides, flows with same names and matching fields but different timeout/priority/cookie shouldn't be considered as identical flows. Instead, we should replace the old one with the new ones. 
We should first check the matching_fileds, then the name. The logic is like:
    if flow2.matching_fields=flow1.matching_fields
        replace flow1 with flow2
    else if flow2.name=flow1.name
        return warning("a flow with the same name exists")
I don't know what is  the mechanism of floodlight to install and store these static flows. As when I query the flows using stats api (/wm/core/switch/all/flow/json), the results have no duplicates. Seems like it just installed one in switch but stored all these identical flows with different names in storage.

**Comment by allewwaly** [comment]
Or we can store the static flows using a nested map like:
key: flow-name value:map<matching_fields, priority/timeout/cookie + actions>
in checkFlow function, check 
```
if the get(key).listkeys()==flow.matching_fields:
     updateFlow (del old and add new)
else listkeys().contains(key):
     warning(return error state)
else
     addFlow
```

**Comment by rizard** [comment]
@allewwaly The static entry pusher is designed to be a dumb list of flows. If a user installs a duplicate flow but with a different key, the static entry pusher does not care. Perhaps we should kick back a warning that this is the case, but it shouldn't be prevented. Feel free to open up a pull request if you would like to add a warning to the HTTP response for a flow push.

**Comment by allewwaly** [comment]
@rizard so does it mean that the static entry pusher actually doesn't install all flows? Because if it install all duplicate flows, it would consume the resources of the switch.

**Comment by rizard** [comment]
@allewwaly the static flow pusher does install the flows. The user of the static flow pusher is fully responsible for managing the flow table. This is by design.

**Comment by allewwaly** [comment]
However, when I query the flow table using stats query api, I can only get
one of them. So is there a non-consistent problem?

2017-03-01 11:23 GMT+08:00 Ryan Izard <notifications@github.com>:

**Comment by rizard** [comment]
@allewwaly let's move this to the floodlight-dev@openflowhub.org email list. Please include relevant documentation of the issue you're having, such as the specific flows you are pushing, the commands you're using to push them, and the API and results you're using to check the flow tables. Information on your specific switch make and model would also be helpful.

If after going through your issue on the mailing list we determine there is a bug, then we can open an issue here.
