### ISSUE TITLE
floodlight get hangup when staticentrypusher push a non-standard flow

### ISSUE THREAD

**Issue by allewwaly** [floodlight/floodlight#737]
It seems that the staticentrypusher doesn't check the prerequisite of a flow matching field, which causes the floodlight get hangup when such a flow is pushed. For example, when the following flow with the udp ports specified but without the ip_proto specified, it would cause the floodlight hangup. 

`{ 'switch': '00:00:00:00:00:00:00:01', 'name': 'flow-1', 'eth_type': '0x800', 'udp_src': '5001','udp_dst': '42443', 'ipv4_src': '10.0.0.2', 'ipv4_dst': '10.0.0.1', 'in_port':'1', 'actions': 'output=2'}`

**Comment by rizard** [comment]
@allewwaly what do you mean "floodlight hangup"? For questions like this, please post to our mailing list floodlight-dev@openflowhub.org. We try to reserve GitHub issues for things we know are bugs.

**Comment by allewwaly** [comment]
> what do you mean "floodlight hangup"?
I mean it get stuck, with no response to any api requests.

> please post to our mailing list floodlight-dev@openflowhub.org. We try to reserve GitHub issues for things we know are bugs.
sorry for that
