### ISSUE TITLE
Can't find org.projectfloodlight.openflow.types folder

### ISSUE THREAD

**Issue by binamkayastha** [floodlight/floodlight#742]
Hi, I was where the code for IPv4Address class was. I tried to find it but it was already compiled in this github project. Is it stored on a different repo?

**Comment by cbarrin** [comment]
That class comes the OpenflowJ libraries. It can be found here:
https://github.com/floodlight/loxigen/blob/2dead4fcabca346e04c0d995e762c09e3751b1eb/java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/IPv4Address.java

For future reference, questions like this need to be asked on the Floodlight developer list:
https://groups.google.com/a/openflowhub.org/forum/#!forum/floodlight-dev
