### ISSUE TITLE
A bug in TopologyInstance: cannot compute paths

### ISSUE THREAD

**Issue by flan01** [floodlight/floodlight#746]
Hello
There is a bug that affects computing paths in TopologyInstance. Sometimes, depending on the topology, Floodlight cannot compute paths because it assumes mistakenly that some switches are not in the same archipelago. The reason is because archipelago/cluster objects are mutable with hashCode() depending on a mutable id (smallest DPID) that can be changed when you merge with another archipelago (or add a cluster). If you add an object to a HashSet then change its hashCode() value, you cannot remove this object from the set. This is exactly what happens inside identifyArchipelagos(). It took me a while to figure out that some archipelago objects are not correctly removed from the HashSet.

Using mutable objects with HashSets is problematic. I suggest revising the implementation of archipelago/cluster. Perhaps consider changing them to immutable or just modifying hashCode().

Thank you,

**Comment by cbarrin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug #](https://trello.com/c/eHvQgSoc/36-bug)

**Comment by cbarrin** [comment]
Thanks for spotting this! Hopefully we got it fixed in pull request #750.
