### ISSUE TITLE
how to set vlanid??

### ISSUE THREAD

**Issue by worker24h** [floodlight/floodlight#754]
hi, do you help me ? how to set vlanid?
The following is code:
flow_vlan_tag_1 = {
	"switch":"00:00:b8:2a:72:d9:4d:d5",
	"name":"brA-flow-vlan-tag-1",
	"cookie":"0",
	"priority":"200",
	"eth_type":"0x0800",
	"in_port":"4",
	"eth_src":"00:16:3e:64:a1:00",
	"eth_dst":"00:16:3e:64:b1:00",
	"ipv4_src":"172.63.10.15",
	"ipv4_dst":"172.63.10.16",
	"active":"true",
	"instruction_apply_actions":"push_vlan=0x8100,set_field=eth_vlan_vid->4196,output=6"
}
but openflow packet(flowmod)  has'nt vlan-id information.

The flowing is original packet:
00 11 (OFPAT_PUSH_VLAN<17>)
00 08 (Length)
81 00 (802.1Q 0x8100)
00 00 (Pad)                  
00 00 (OFPAT_OUTPUT)
00 10 (Length)
00 00 00 06 (Output Port=6)
ff ff 
00 00 00 00 00 00

**Comment by geddings-bsn** [comment]
Are your expected packets matching on your flow? You may need to match on the VLAN. Check out this page for the necessary matches and actions:
https://floodlight.atlassian.net/wiki/display/floodlightcontroller/Static+Entry+Pusher+API#StaticEntryPusherAPI-OptionalFlowEntryMatchFields

I'm going to close this issue. These questions need to go in the Floodlight Developers mailing list. Find that here:
https://groups.google.com/a/openflowhub.org/forum/#!forum/floodlight-dev
