### ISSUE TITLE
Topology Manager does not build BDDP packet out correctly for OpenFlow 1.5

### ISSUE THREAD

**Issue by geddings** [floodlight/floodlight#764]
When building a BDDP packet out message, the topology manager uses the "setInPort" method. This works for OF1.0-1.4, but the in port was replaced with a match in OF1.5. Therefore, when a BDDP packet out is created, an exception is thrown if the switch is using OF1.5.

Where the exception is caused:
https://github.com/floodlight/floodlight/blob/master/src/main/java/net/floodlightcontroller/topology/TopologyManager.java#L748

Utility method that can be used to fix the issue:
https://github.com/floodlight/floodlight/blob/master/src/main/java/net/floodlightcontroller/util/OFMessageUtils.java#L125

**Comment by geddings** [comment]
Same problem in forwardingbase here:
https://github.com/floodlight/floodlight/blob/master/src/main/java/net/floodlightcontroller/routing/ForwardingBase.java#L343

**Comment by QingWang0909** [comment]
@geddings Thanks for pointing this out! I just sent a pull request to fix this issue -- https://github.com/floodlight/floodlight/pull/765. Once you have some time available, please take a look at the fix and see if that looks good. 

Feel free to close this issue if everything looks fine. Thanks again!

**Comment by QingWang0909** [comment]
Just for posterity and documentation purpose, #765 is the patch for this issue.
