### ISSUE TITLE
unable to run quantum app in floodlight VM

### ISSUE THREAD

**Issue by pervez8ktt** [floodlight/floodlight#773]
ERROR [n.f.core.Main] Could not read config file: No such file or directory: src/main/resources/quantum.properties

**Comment by QingWang0909** [comment]
@pervez8ktt Do you mind to post this question to floodlight-dev@openflowhub.org? We typically leave "Issues" to resolve Floodlight bugs. Please forward this question to our Floodlight mailing list above, we'd happy to help you there.

I'll close this Issue for now. Thanks!
