### ISSUE TITLE
Extra object creation

### ISSUE THREAD

**Issue by pervez8ktt** [floodlight/floodlight#775]
https://github.com/floodlight/floodlight/blob/14e52d07bbbd9e32b2024c58817b084ea3cbcd50/src/main/java/net/floodlightcontroller/routing/web/PathResource.java#L66

At Above link I think you can use result object 

i.e. result.getPath();

If not then kindly explain

and why you didn't send all result object?
Is hop_count into this object is correct and usable?

**Comment by QingWang0909** [comment]
@pervez8ktt We typically reserve "issue" as a place to resolve Floodlight bugs. Is this a potential Floodlight bug that needs to be resolved? If not, I'll close this issue for now and please post your questions to our emailing list so we can discuss there. Feel free to re-open it if you think this is a bug.  

Thanks very much for your understanding!
