### ISSUE TITLE
Bad computation of elapsed time between polling of switch. In /src/main/java/net/floodlightcontroller/statistics/StatisticsCollector.java

### ISSUE THREAD

**Issue by xslizikm** [floodlight/floodlight#806]
**Describe the bug**
Bad computation of elapsed time between polling of switch. In /src/main/java/net/floodlightcontroller/statistics/StatisticsCollector.java 	
long timeDifSec = ((System.nanoTime() - spb.getStartTime_ns()) / 1000000) / MILLIS_PER_SEC;
Using type long for this computation just cuts everything after decimal separator and it results in unprecise computation on lines 	
U64.ofRaw((rxBytesCounted.getValue() * BITS_PER_BYTE) / timeDifSec) and 	U64.ofRaw((txBytesCounted.getValue() * BITS_PER_BYTE) / timeDifSec), 

**To Reproduce**
1. print out value variable timeDifSec, and create second one, that is cast to double, like this : 
double timeDifSec1 = ((double)(System.nanoTime() - (double)spb.getStartTime_ns())/1000000) / MILLIS_PER_SEC ;
and print out that variable aswell
2. set port statistics collector interval to 2 seconds
3. Run floodlight and check that timeDiffSec of type long has values either 1 or 2 and timeDiffSec1 of type double has values around 2 like 1.99 etc. Which means that current implementation skews calculation of bits-per-second by nearly 100 percent when it just rounds for example timeDifSec of 1.99s to 1s

**Solution proposal**
I use kinda ugly workaround, because I just need to monitor small traffic in network, so my solution looks like this: 
double timeDifSec1 = ((double)(System.nanoTime() - (double)spb.getStartTime_ns())/1000000) / MILLIS_PER_SEC ;
U64.ofRaw( Math.round((double)( rxBytesCounted.getValue() * BITS_PER_BYTE) / timeDifSec1))
U64.ofRaw( Math.round((double)( txBytesCounted.getValue() * BITS_PER_BYTE) / timeDifSec1))
It's for sure not ideal solution but it gives much better results as one that is implemented

 - Floodlight Version [master]
 - OS: [Ubuntu]

**Comment by qingwang-bsn** [comment]
@xslizikm thanks for point it out! Made fix here: #814.
