### ISSUE TITLE
openflowpipelinefactory.java is missed ??

### ISSUE THREAD

**Issue by ahmad8746** [floodlight/floodlight#808]
**Describe the bug**
I am using floodlight master. i am trying to make a secure connection using SSL OR TLS. to do that i have to manipulate a class located in "src/main/java/net/floodlightcontroller/core/internal/OpenFlowPipelineFactory.java"
i am using a tutorial in "https://floodlight.atlassian.net/wiki/spaces/floodlightcontroller/pages/4325395/How+to+add+TLS+SSL+support+b+t+Java+s+Netty+and+Open+vSwitch"
how ever. my floodlight master doest not contain a class called "OpenFlowPipelineFactory.java" in the above mentioned location. 
Any one has an idea to help me
Thanks

**Expected behavior**

i expected that the floodlight master contain openflowpipelinefactory.java as it descripes in "https://floodlight.atlassian.net/wiki/spaces/floodlightcontroller/pages/4325395/How+to+add+TLS+SSL+support+b+t+Java+s+Netty+and+Open+vSwitch" to secure a channel between floodlight and ovs

**Desktop (please complete the following information):**
 - Floodlight Version [e.g. master, v1.2 etc.]
 - OS: [e.g. Ubuntu, MacOS, Windows etc.]

**Comment by QingWang0909** [comment]
Please use Floodlight v1.1 branch -- openflowpipelinefactory is there. Looks like we deprecated it since v1.2.
