### ISSUE TITLE
Error appear when import Main.Java in the net.floodlightcontroller.core ?

### ISSUE THREAD

**Issue by raghdaaljaff** [floodlight/floodlight#817]
i have floodlight master branch iam trying to import the Main.Java  and theres error appear when i run the Main.Java 
![error floodlight](https://user-images.githubusercontent.com/23114264/53046086-e482e380-3497-11e9-88a5-e9c5d15aa1a4.png)

How i solve this error appear in the picture above?

**Comment by raghdaaljaff** [comment]
@QingWang0909 ,brother can you help in my issue and thanks

**Comment by qingwang-bsn** [comment]
Please refer to the thread here, it is the same problem:  https://groups.io/g/floodlight/topic/error_in_floodlight_import/30156714?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,30156714
