### ISSUE TITLE
Error while running FloodLight in Netbeans 8.2

### ISSUE THREAD

**Issue by kopida** [floodlight/floodlight#823]
Hi dear,
I have tried to run FloodLight in Netbeans. There is no error while I import the FloodLight 1.2 to the Netbeans, but an error happens when I run the main program. I would like to run FloodLight in Netbeans because I want to connect my java program that runs in Netbeans to the FloodLight and configure the program via the FloodLight.

Can you please help me to take a look at the error below and suggest a solution to the issue.
I really appreciate help.

The error is:
15:56:33.049 [main] INFO  n.f.c.module.FloodlightModuleLoader - Loading modules from src\main\resources\floodlightdefault.properties
15:56:33.063 [main] DEBUG n.f.c.module.FloodlightModuleLoader - Starting module loader
15:56:33.075 [main] ERROR net.floodlightcontroller.core.Main - Exception in main
net.floodlightcontroller.core.module.FloodlightModuleException: Module net.floodlightcontroller.jython.JythonDebugInterface not found
	at net.floodlightcontroller.core.module.FloodlightModuleLoader.traverseDeps(FloodlightModuleLoader.java:313) ~[classes/:na]
	at net.floodlightcontroller.core.module.FloodlightModuleLoader.loadModulesFromList(FloodlightModuleLoader.java:287) ~[classes/:na]
	at net.floodlightcontroller.core.module.FloodlightModuleLoader.loadModulesFromConfig(FloodlightModuleLoader.java:235) ~[classes/:na]
	at net.floodlightcontroller.core.Main.main(Main.java:71) ~[classes/:na]

BUILD FAILURE
------------------------------------------------------------------------
Total time: 2.338s
Finished at: Fri May 10 15:56:33 AEST 2019
Final Memory: 6M/119M
------------------------------------------------------------------------
Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project floodlight: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by geddings** [comment]
Hi! What does your run configuration in Netbeans looks like? How are you compiling Floodlight? 

I would also suggest checking out the mailing list [here.](https://groups.io/g/floodlight/topics) It's possible that someone has already run across this issue and may be able to help!

**Comment by kopida** [comment]
Hi geddings, many thanks for your response.

I tried to run the main program belonging to the net.floodlightcontroller.core package. Please see the picture below.

<img width="949" alt="error-running FloodLight main program" src="https://user-images.githubusercontent.com/18657081/57576491-34c07f00-74a4-11e9-94a0-a0fdb7323702.png">


Please advice me a way to solve it. I really appreciate your help.
Chau

**Comment by QingWang0909** [comment]
@kopida Hi Kopida, you shall configure Floodlight as a Maven project in Netbeans and compile it and then run it as a Maven project. Try to do that and see. You can also compile Floodlight from terminal by "mvn package", if that works then that means something misconfigured in your IDE (Netbeans).

**Comment by kopida** [comment]
Hi QingWang. the floodlight has been imported as a Maven project, but there is the same error. Please see the image below
<img width="946" alt="error-running FloodLight main program as a Maven project" src="https://user-images.githubusercontent.com/18657081/57755979-977c7980-7735-11e9-8235-b04702a1eecd.png">

Please give me a suggestion to solve it. Many thanks for your support.
Kopida

**Comment by kopida** [comment]
Hi QingWang, I found the issue. It is because of an added code about sending a packet out the message. I learned the code from the link below:
https://floodlight.atlassian.net/wiki/spaces/floodlightcontroller/pages/9142281/How+to+Create+a+Packet+Out+Message

The code causes the error is as follows:
OFPacketOut po = mySwitch.getOFFactory().buildPacketOut()
                                .setData(serializedData)
                                .setActions((List<OFAction>) Collections.singleton((OFAction) 
                                    mySwitch.getOFFactory().actions().output(OFPort.FLOOD, 0xffFFffFF)))
                                .setInPort(OFPort.CONTROLLER)
                                .build();
                        mySwitch.write(po);
